export const sagasConstants = {
   SAGA_CHANGE_COORDINATES_CITY: "SAGA_CHANGE_COORDINATES_CITY",
   SAGA_CHANGE_COORDINATES_GEOGRAPH: "SAGA_CHANGE_COORDINATES_GEOGRAPH",
   SAGA_OPEN_WEATHER_API: "SAGA_OPEN_WEATHER_API",
   SAGA_WEATHER_BIT_API: "SAGA_WEATHER_BIT_API",
}
